export const StaticDataArray=[

    {src:"https://www.youtube.com/embed/6oAdJjzXQS8",
    imgsrc:"https://img.youtube.com/vi/6oAdJjzXQS8/0.jpg",
    title:"YouTube video player",
    name:"Relaxing Piano Music & Water Sounds 24/7 - Ideal for Stress Relief and Healing",
    desc:"The OCB (One Conscious Breath) relaxing music series help you calm down. These music are great for relaxing, meditation, yoga, massage, studying, reading, sleeping, healing, stress relief, working and more. Original, calming and peaceful tunes created and uploaded to YouTube every week.",
    id:4,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/35npVaFGHMY",
    imgsrc:"https://img.youtube.com/vi/35npVaFGHMY/0.jpg",
    title:"YouTube video player",
    name:"Welcome to India ! [CINEMATIC TRAVEL FILM]",
    desc:"vanlifing through India was an impressive experience for me, a country where magic and incredible landscapes are everywhere. This is a part of mindblowing scenes i saw during this trip from himalayan mountains , to extreme south of Kerala.",
    id:8,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/CYYtLXfquy0",
    imgsrc:"https://img.youtube.com/vi/CYYtLXfquy0/0.jpg",
    title:"YouTube video player",
    name:"AVATAR 2 THE WAY OF WATER Trailer (4K ULTRA HD) 2022",
    desc:"AVATAR 2 THE WAY OF WATER Trailer (4K ULTRA HD) 2022. First Trailer For Avatar 2 The Way Of Water.",
    id:3,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/ij-K0MTTM4c",
    imgsrc:"https://img.youtube.com/vi/ij-K0MTTM4c/0.jpg",
    title:"YouTube video player",
    name:"Mysore Masal Dosa | Masal Roast Recipe | Masala Dosa | Mysore Masala Dosa | The Tiny Foods",
    desc:"Masal Dosa (Roast recipe) is one of the most famous street food item in India, miniature mysore masala roast is made with kids kitchen set (Miniature Utensils) we already made many types of dosa but this Mysore masal dosa is most famous and unique food in India so we tried in our tiny foods to entertain you so hope you like it.",
    id:9,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/e7vsPqNmlFI",
    imgsrc:"https://img.youtube.com/vi/e7vsPqNmlFI/0.jpg",
    title:"YouTube video player",
    name:"amazing cake mass production!",
    desc:"amazing cake mass production! making dynamite fresh cream cake in cake factory - korean street food.",
    id:10,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/oKP1THYIsg4",
    imgsrc:"https://img.youtube.com/vi/oKP1THYIsg4/0.jpg",
    title:"YouTube video player",
    name:"most satisfying! korean best cake factory mass production top3",
    desc:"most satisfying! korean best cake factory mass production top3 - korean street food.Shooting videos all about street food traveling abroad.Always trying to make good quality videos.Hope to watch my videos deliciously!",
    id:11,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/IgAnj6r1O48",
    imgsrc:"https://img.youtube.com/vi/IgAnj6r1O48/0.jpg",
    title:"YouTube video player",
    name:"10 Best Places to Visit in India - Travel Video",
    desc:"India is an enormous and diverse destination. Bordered by seven different countries, not to mention the Arabian Sea and the Bay of Bengal, means that there are many different sides to the country. More than 20 official languages, multiple religions and a variety of cuisines exist within India’s borders. To truly experience the breadth of Indian culture and history, travel is key. Here’s a look at the best places to visit in India.",
    id:12,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/bKaVhXn49xY",
    imgsrc:"https://img.youtube.com/vi/bKaVhXn49xY/0.jpg",
    title:"YouTube video player",
    name:"75 000 h.p. The Biggest Nuclear Icebreaker",
    desc:"This video was shot in the Arctic Ocean in March 2018. For 7 days our crew passed through the Barents Sea to Karsky around the Novaya Zemlya archipelago on the nuclear icebreaker Yamal - we saw the northern lights and polar bears, watched the ships stuck in the ice being towed, and were very cold.",
    id:13,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/hQAHSlTtcmY",
    imgsrc:"https://img.youtube.com/vi/hQAHSlTtcmY/0.jpg",
    title:"YouTube video player",
    name:"Learn React In 30 Minutes",
    desc:"Understand how the code is executed in JavaScript. How an Execution Context is created and how the Call Stack works. Behind the scenes, there are a lot of things happening in JS Engine when the code is executed. All core fundamentals are covered in this video with examples.",
    id:5,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/iLWTnMzWtj4",
    imgsrc:"https://img.youtube.com/vi/iLWTnMzWtj4/0.jpg",
    title:"YouTube video player",
    name:"How JavaScript Code is executed? ❤️& Call Stack | Namaste JavaScript Ep. 2",
    desc:"Understand how the code is executed in JavaScript. How an Execution Context is created and how the Call Stack works. Behind the scenes, there are a lot of things happening in JS Engine when the code is executed. All core fundamentals are covered in this video with examples.",
    id:1,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/fYq5PXgSsbE",
    imgsrc:"https://img.youtube.com/vi/fYq5PXgSsbE/0.jpg",
    title:"YouTube video player",
    name:"Learn Flexbox in 15 Minutes",
    desc:"Understand how the code is executed in JavaScript. How an Execution Context is created and how the Call Stack works. Behind the scenes, there are a lot of things happening in JS Engine when the code is executed. All core fundamentals are covered in this video with examples.",
    id:2,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/iYoXFg5D4NU",
    imgsrc:"https://img.youtube.com/vi/iYoXFg5D4NU/0.jpg",
    title:"YouTube video player",
    name:"Work Like Me, To Become The Best - Cristiano Ronaldo (motivation)",
    desc:"Cristiano Ronaldo Motivation - Work Like Me, To Become The BestCristiano Ronaldo has given his everything to achieve this version of himself. “Blood, toil, and sweat” are the main Principles of the Portuguese player. He's one of the best football players in the world.",
    id:6,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/mMQSY0d7D1U",
    imgsrc:"https://img.youtube.com/vi/mMQSY0d7D1U/0.jpg",
    title:"YouTube video player",
    name:"Neeraj Chopra does India proud again; Clinches gold in Finland despite nasty fall",
    desc:"Olympic champion Neeraj Chopra won a gold medal at the Kuortane Games in Finland. He registered the win after throwing 86.69m on his first attempt. However, due to rain, Chopra had a nasty fall while making his third throw, after which he didn't throw but that first throw was enough for gold for Neeraj.",
    id:7,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/sWpm-RsRmWA",
    imgsrc:"https://img.youtube.com/vi/sWpm-RsRmWA/0.jpg",
    title:"YouTube video player",
    name:"BRAHMĀSTRA OFFICIAL TRAILER | Hindi | Amitabh | Ranbir | Alia | Ayan | In Cinemas 9th September",
    desc:"BRAHMĀSTRA – the Trilogy, is a 3-part film franchise and the beginning of India’s first original universe The Astraverse.It is a new original cinematic universe inspired by deeply rooted concepts and tales from Indian history but set in the modern world, with epic storytelling of fantasy, adventure, good vs evil, love and hope; all told using cutting edge technology and never-seen-before visual spectacles.",
    id:7,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    },
    {src:"https://www.youtube.com/embed/JfVOs4VSpmA",
    imgsrc:"https://img.youtube.com/vi/JfVOs4VSpmA/0.jpg",
    title:"YouTube video player",
    name:"SPIDER-MAN: NO WAY HOME - Official Trailer (HD)",
    desc:"For the first time in the cinematic history of Spider-Man, our friendly neighborhood hero's identity is revealed, bringing his Super Hero responsibilities into conflict with his normal life and putting those he cares about most at risk. When he enlists Doctor Strange’s help to restore his secret, the spell tears a hole in their world, releasing the most powerful villains who’ve ever fought a Spider-Man in any universe. Now, Peter will have to overcome his greatest challenge yet, which will not only forever alter his own future but the future of the Multiverse.",
    id:7,
    like:0,
    dislike:0,
    Playlist:0,
    watchlater:0
    }
    
]